import {
  siApachekafka,
  siAppwrite,
  siArgo,
  siBun,
  siC,
  siCplusplus,
  siDeepgram,
  siDeno,
  siDjango,
  siDocker,
  siDrizzle,
  siElevenlabs,
  siExpress,
  siFastapi,
  siFirebase,
  siFlask,
  siFramer,
  siGin,
  siGithub,
  siGithubactions,
  siGnubash,
  siGo,
  siGooglegemini,
  siGrafana,
  siGraphql,
  siHelm,
  siHono,
  siHtmx,
  siJavascript,
  siJenkins,
  siJira,
  siJsonwebtokens,
  siK3s,
  siKubernetes,
  siLangchain,
  siLeetcode,
  siLinux,
  siModelcontextprotocol,
  siMongodb,
  siMongoose,
  siMui,
  siMysql,
  siNeon,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNumpy,
  siOllama,
  siOpenjdk,
  siOpentelemetry,
  siPostgresql,
  siPrisma,
  siProbot,
  siPrometheus,
  siPython,
  siPytorch,
  siRailway,
  siReact,
  siReactquery,
  siRedis,
  siRedux,
  siRender,
  siSanity,
  siSass,
  siShadcnui,
  siSocketdotio,
  siSolidity,
  siSonarqubeserver,
  siSpring,
  siSqlite,
  siSupabase,
  siTailwindcss,
  siTerraform,
  siThirdweb,
  siTrivy,
  siTurso,
  siTypescript,
  siVercel,
  siVite,
  siWebassembly,
} from "simple-icons";
import { markColors, type SimpleIcon, type TechMark } from "./techIcons";

/**
 * Skill names from profile.json that have a brand mark. Anything not listed
 * renders as a plain chip. Server-only: SkillChips resolves these to paths.
 */
const MARKS: Record<string, SimpleIcon> = {
  Go: siGo,
  Python: siPython,
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  Java: siOpenjdk,
  C: siC,
  "C++": siCplusplus,
  Bash: siGnubash,
  WebAssembly: siWebassembly,
  "Node.js": siNodedotjs,
  Deno: siDeno,
  Express: siExpress,
  "Spring Boot": siSpring,
  Django: siDjango,
  FastAPI: siFastapi,
  Flask: siFlask,
  Gin: siGin,
  Bun: siBun,
  Hono: siHono,
  HTMX: siHtmx,
  GraphQL: siGraphql,
  "Socket.IO": siSocketdotio,
  "JWT auth": siJsonwebtokens,
  React: siReact,
  "Next.js": siNextdotjs,
  "Tailwind CSS": siTailwindcss,
  Redux: siRedux,
  "shadcn/ui": siShadcnui,
  "TanStack Query and Router": siReactquery,
  "Material UI": siMui,
  SCSS: siSass,
  Vite: siVite,
  "Framer Motion": siFramer,
  "Sanity CMS": siSanity,
  PostgreSQL: siPostgresql,
  MySQL: siMysql,
  MongoDB: siMongodb,
  Redis: siRedis,
  SQLite: siSqlite,
  Turso: siTurso,
  Neon: siNeon,
  Supabase: siSupabase,
  Firebase: siFirebase,
  Appwrite: siAppwrite,
  Drizzle: siDrizzle,
  Prisma: siPrisma,
  Mongoose: siMongoose,
  Kafka: siApachekafka,
  Nginx: siNginx,
  "Low-latency C++": siCplusplus,
  Docker: siDocker,
  Kubernetes: siKubernetes,
  Helm: siHelm,
  "Kind and k3s": siK3s,
  "GitHub Actions": siGithubactions,
  ArgoCD: siArgo,
  GitOps: siArgo,
  Jenkins: siJenkins,
  Trivy: siTrivy,
  SonarQube: siSonarqubeserver,
  Vercel: siVercel,
  Render: siRender,
  Railway: siRailway,
  Linux: siLinux,
  "Infrastructure as Code": siTerraform,
  Prometheus: siPrometheus,
  Grafana: siGrafana,
  OpenTelemetry: siOpentelemetry,
  LangChain: siLangchain,
  "LLM agents and MCP": siModelcontextprotocol,
  Gemini: siGooglegemini,
  Ollama: siOllama,
  Deepgram: siDeepgram,
  ElevenLabs: siElevenlabs,
  "Neural networks": siPytorch,
  "NumPy and pandas": siNumpy,
  "Smart contracts": siSolidity,
  Thirdweb: siThirdweb,
  "Git and GitHub": siGithub,
  "Probot automation": siProbot,
  "Jira and Agile": siJira,
  "Competitive programming": siLeetcode,
  "Web scraping (BeautifulSoup)": siPython,
};

export function markForSkill(name: string): TechMark | undefined {
  const icon = MARKS[name];
  if (!icon) return undefined;
  const { dark, light } = markColors(icon.hex);
  return { path: icon.path, title: icon.title, dark, light };
}
