import {
  siApachekafka,
  siArgo,
  siBun,
  siCplusplus,
  siDjango,
  siDocker,
  siFastapi,
  siFirebase,
  siFlask,
  siGin,
  siGit,
  siGithubactions,
  siGnubash,
  siGo,
  siGrafana,
  siGraphql,
  siHelm,
  siHono,
  siJavascript,
  siJenkins,
  siKubernetes,
  siLangchain,
  siLinux,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siOpenjdk,
  siOpentelemetry,
  siPostgresql,
  siPrometheus,
  siPython,
  siReact,
  siRedis,
  siSpring,
  siSqlite,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siWebassembly,
} from "simple-icons";
import type { SimpleIcon } from "./techIcons";

/**
 * Everything shipped with so far, in the order it reads best: languages,
 * frontend, backend, data, infrastructure, observability, AI. Imported only
 * by the server-rendered StackStrip, so none of this reaches client JS.
 */
export const STACK: { icon: SimpleIcon; label?: string }[] = [
  { icon: siGo },
  { icon: siPython },
  { icon: siTypescript },
  { icon: siJavascript },
  { icon: siCplusplus },
  { icon: siOpenjdk, label: "Java" },
  { icon: siGnubash, label: "Bash" },
  { icon: siWebassembly, label: "WebAssembly" },
  { icon: siReact },
  { icon: siNextdotjs },
  { icon: siTailwindcss, label: "Tailwind" },
  { icon: siNodedotjs },
  { icon: siSpring },
  { icon: siDjango },
  { icon: siFastapi },
  { icon: siFlask },
  { icon: siGin },
  { icon: siBun },
  { icon: siHono },
  { icon: siGraphql },
  { icon: siPostgresql },
  { icon: siMysql },
  { icon: siMongodb },
  { icon: siRedis },
  { icon: siSqlite },
  { icon: siSupabase },
  { icon: siFirebase },
  { icon: siApachekafka, label: "Kafka" },
  { icon: siDocker },
  { icon: siKubernetes },
  { icon: siHelm },
  { icon: siNginx },
  { icon: siGithubactions, label: "GitHub Actions" },
  { icon: siArgo, label: "ArgoCD" },
  { icon: siJenkins },
  { icon: siLinux },
  { icon: siGit },
  { icon: siGrafana },
  { icon: siPrometheus },
  { icon: siOpentelemetry, label: "OpenTelemetry" },
  { icon: siLangchain },
];
